services:
  desktop-vnc:
    build: .      
    ports:
      - "6081:80"
      - "5900:5900"
    env_file:
      - config/vnc_config.env
    volumes:
      - "./persistance/:/home/seba/persistance"
      - "./Desktop/:/home/seba/Desktop"

